/*
 * This file is generated by jOOQ.
 */
package com.sdakhniy.kobzar.model.tables.records;


import com.sdakhniy.kobzar.model.tables.Words;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WordsRecord extends UpdatableRecordImpl<WordsRecord> implements Record5<Long, String, String[], Integer, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.words.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.words.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.words.word</code>.
     */
    public void setWord(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.words.word</code>.
     */
    public String getWord() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.words.letters</code>.
     */
    public void setLetters(String[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.words.letters</code>.
     */
    public String[] getLetters() {
        return (String[]) get(2);
    }

    /**
     * Setter for <code>public.words.unique_number</code>.
     */
    public void setUniqueNumber(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.words.unique_number</code>.
     */
    public Integer getUniqueNumber() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.words.rank</code>.
     */
    public void setRank(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.words.rank</code>.
     */
    public Double getRank() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String[], Integer, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String[], Integer, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Words.WORDS.ID;
    }

    @Override
    public Field<String> field2() {
        return Words.WORDS.WORD;
    }

    @Override
    public Field<String[]> field3() {
        return Words.WORDS.LETTERS;
    }

    @Override
    public Field<Integer> field4() {
        return Words.WORDS.UNIQUE_NUMBER;
    }

    @Override
    public Field<Double> field5() {
        return Words.WORDS.RANK;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getWord();
    }

    @Override
    public String[] component3() {
        return getLetters();
    }

    @Override
    public Integer component4() {
        return getUniqueNumber();
    }

    @Override
    public Double component5() {
        return getRank();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getWord();
    }

    @Override
    public String[] value3() {
        return getLetters();
    }

    @Override
    public Integer value4() {
        return getUniqueNumber();
    }

    @Override
    public Double value5() {
        return getRank();
    }

    @Override
    public WordsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WordsRecord value2(String value) {
        setWord(value);
        return this;
    }

    @Override
    public WordsRecord value3(String[] value) {
        setLetters(value);
        return this;
    }

    @Override
    public WordsRecord value4(Integer value) {
        setUniqueNumber(value);
        return this;
    }

    @Override
    public WordsRecord value5(Double value) {
        setRank(value);
        return this;
    }

    @Override
    public WordsRecord values(Long value1, String value2, String[] value3, Integer value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WordsRecord
     */
    public WordsRecord() {
        super(Words.WORDS);
    }

    /**
     * Create a detached, initialised WordsRecord
     */
    public WordsRecord(Long id, String word, String[] letters, Integer uniqueNumber, Double rank) {
        super(Words.WORDS);

        setId(id);
        setWord(word);
        setLetters(letters);
        setUniqueNumber(uniqueNumber);
        setRank(rank);
    }
}
