/*
 * This file is generated by jOOQ.
 */
package com.sdakhniy.kobzar.model;


import com.sdakhniy.kobzar.model.tables.Words;
import com.sdakhniy.kobzar.model.tables.records.WordsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<WordsRecord> WORDS_PK = Internal.createUniqueKey(Words.WORDS, DSL.name("words_pk"), new TableField[] { Words.WORDS.ID }, true);
}
