/*
 * This file is generated by jOOQ.
 */
package com.sdakhniy.kobzar.model;


import com.sdakhniy.kobzar.model.tables.Words;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.words</code>.
     */
    public static final Words WORDS = Words.WORDS;
}
